# Generated by Django 3.2.6 on 2021-11-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('username', models.CharField(max_length=1000, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('role', models.CharField(choices=[('Merchant', 'Merchant'), ('Buyer', 'Buyer')], default='Buyer', max_length=1000)),
                ('address_line1', models.CharField(blank=True, max_length=1000, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=1000, null=True)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('telephone', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('organization', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generated_RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Other', 'Other')], default='Mechanical', max_length=1000, null=True)),
                ('RFQ_type', models.CharField(blank=True, choices=[('SI', 'SI'), ('NSI', 'NSI')], default='SI', max_length=1000, null=True)),
                ('Item_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('Model_Information', models.CharField(blank=True, max_length=1000, null=True)),
                ('Delivery_Time_Duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('Price_Range', models.CharField(blank=True, max_length=1000, null=True)),
                ('RFQ_image', models.ImageField(blank=True, default=None, upload_to='RFQ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procureapp.procurement_user')),
            ],
        ),
    ]
