# Generated by Django 3.2.6 on 2021-11-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generated_rfq',
            name='RFQ_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=1000, null=True),
        ),
    ]
