# Generated by Django 3.2.9 on 2021-11-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='procure_user_db',
            new_name='procure_userdb',
        ),
    ]
