# Generated by Django 3.2.9 on 2021-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0002_rename_procure_user_db_procure_userdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procure_userdb',
            name='address_line1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='address_line2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='role',
            field=models.CharField(choices=[('Merchant', 'Merchant'), ('Buyer', 'Buyer')], default='Buyer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='telephone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
