# Generated by Django 3.2.9 on 2021-11-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0003_auto_20211126_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procure_userdb',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='role',
            field=models.CharField(choices=[('Merchant', 'Merchant'), ('Buyer', 'Buyer')], default='Buyer', max_length=50),
        ),
    ]
