# Generated by Django 3.2.6 on 2021-12-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0003_auto_20211201_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurement_user',
            name='email',
        ),
    ]
