# Generated by Django 3.2.9 on 2021-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0004_auto_20211126_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procure_userdb',
            options={'verbose_name_plural': 'Procure User DB'},
        ),
        migrations.AddField(
            model_name='procure_userdb',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='procure_userdb',
            name='organization',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
