# Generated by Django 3.2.6 on 2021-12-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0004_remove_procurement_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement_user',
            name='email',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
