# Generated by Django 3.2.9 on 2021-11-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0005_auto_20211127_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procure_userdb',
            name='role',
            field=models.CharField(choices=[('Merchant', 'Merchant'), ('Buyer', 'Buyer')], max_length=50),
        ),
    ]
