# Generated by Django 3.2.6 on 2021-12-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0006_generated_rfq_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='Delivery_Time_Duration',
            new_name='delivery_time_duration',
        ),
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='Item_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='Model_Information',
            new_name='model_information',
        ),
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='Price_Range',
            new_name='price_range',
        ),
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='RFQ_image',
            new_name='rfq_image',
        ),
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='RFQ_status',
            new_name='rfq_status',
        ),
        migrations.RenameField(
            model_name='generated_rfq',
            old_name='RFQ_type',
            new_name='rfq_type',
        ),
    ]
