# Generated by Django 3.2.9 on 2021-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0006_alter_procure_userdb_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procure_userdb',
            name='role',
            field=models.CharField(choices=[('Merchant', 'Merchant'), ('Buyer', 'Buyer')], default='Buyer', max_length=50),
        ),
    ]
