# Generated by Django 3.2.6 on 2021-11-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0007_alter_procure_userdb_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procure_userdb',
            old_name='id',
            new_name='user_id',
        ),
    ]
