# Generated by Django 3.2.6 on 2021-11-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0008_rename_id_procure_userdb_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procure_userdb',
            old_name='user_id',
            new_name='userid',
        ),
    ]
