# Generated by Django 3.2.6 on 2021-11-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0009_rename_user_id_procure_userdb_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procure_userdb',
            old_name='userid',
            new_name='user_id',
        ),
    ]
