# Generated by Django 3.2.6 on 2022-04-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0009_auto_20220406_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedrfq',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='procurementuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
