# Generated by Django 3.2.6 on 2021-11-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0010_rename_userid_procure_userdb_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='procure_userdb',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='user_id',
            field=models.PositiveIntegerField(),
        ),
    ]
