# Generated by Django 3.2.6 on 2021-11-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procureapp', '0014_auto_20211128_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procure_userdb',
            name='address_line1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='address_line2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='organization',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='postal_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='telephone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='procure_userdb',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
