# Generated by Django 3.2.6 on 2021-12-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customized_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fast_dispatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='featured_products',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ready_to_ship',
            field=models.BooleanField(default=False),
        ),
    ]
