# Generated by Django 3.2.6 on 2021-12-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0002_auto_20211205_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
