# Generated by Django 3.2.9 on 2021-11-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0003_alter_userdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
