# Generated by Django 3.2.6 on 2021-12-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0003_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='address_line1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='address_line2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='mobile',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='password',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='postal_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='telephone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
