# Generated by Django 3.2.6 on 2021-12-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0004_auto_20211206_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='user_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
