# Generated by Django 3.2.9 on 2021-11-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0004_alter_userdb_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='product_category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='product_inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterModelOptions(
            name='userdb',
            options={'verbose_name_plural': 'User DB'},
        ),
    ]
