# Generated by Django 3.2.6 on 2021-12-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0005_userdb_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='mobile',
            new_name='phone',
        ),
    ]
