# Generated by Django 3.2.6 on 2021-12-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0006_rename_mobile_userdb_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdb',
            options={'verbose_name_plural': 'User'},
        ),
    ]
