# Generated by Django 3.2.6 on 2021-12-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0007_alter_userdb_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='RFQ'),
        ),
    ]
