# Generated by Django 3.2.6 on 2021-12-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0012_auto_20211209_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
