# Generated by Django 3.2.6 on 2021-12-09 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0013_rename_product_id_cart_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
