# Generated by Django 3.2.6 on 2021-12-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0013_rename_product_id_cart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.userdb'),
        ),
        migrations.AlterField(
            model_name='userdb',
            name='role',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Buyer', 'Buyer')], default='Buyer', max_length=50),
        ),
    ]
