# Generated by Django 3.2.6 on 2021-12-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0014_auto_20211221_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='bankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(blank=True, max_length=50, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('accountIfsc', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.userdb')),
            ],
            options={
                'verbose_name_plural': 'Bank',
            },
        ),
    ]
