# Generated by Django 3.2.6 on 2021-12-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0015_bankdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='aadhaar',
            field=models.ImageField(blank=True, null=True, upload_to='Aadhaar_images'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userdb',
            name='pan',
            field=models.ImageField(blank=True, null=True, upload_to='Pan_images'),
        ),
    ]
