# Generated by Django 3.2.6 on 2021-12-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0016_rename_user_id_userdb_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdb',
            old_name='userid',
            new_name='user_id',
        ),
    ]
