# Generated by Django 3.2.6 on 2021-12-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0019_auto_20211227_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='gstNo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
