# Generated by Django 4.0.1 on 2022-01-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0024_alter_product_sale_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.productinventory'),
        ),
    ]
