# Generated by Django 4.0.1 on 2022-02-02 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0029_alter_product_maximum_order_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
    ]
