# Generated by Django 4.0.1 on 2022-02-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0030_remove_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_choice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
