# Generated by Django 3.2.6 on 2022-02-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0037_alter_bankdetail_accountifsc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('shipping_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.userdb')),
            ],
        ),
    ]
