# Generated by Django 3.2.6 on 2022-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0039_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AddField(
            model_name='orders',
            name='order_quantity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
