# Generated by Django 3.2.6 on 2022-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0041_contact_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
