# Generated by Django 3.1.4 on 2022-04-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0043_auto_20220406_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hot_selling_products',
            field=models.BooleanField(default=False),
        ),
    ]
