# Generated by Django 3.1.4 on 2022-04-07 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0044_product_hot_selling_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maximum_order_quantity',
            new_name='minimum_order_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='terms',
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.productinventory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_choice',
            field=models.CharField(blank=True, choices=[('Add Price', 'Add Price'), ('Price according to quantity', 'Price according to quantity')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='paymentTermFields',
        ),
    ]
