# Generated by Django 3.1.4 on 2022-04-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0046_auto_20220407_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_choice',
            field=models.CharField(blank=True, choices=[('Add Price', 'Add Price'), ('Price according to quantity', 'Price according to quantity')], default='Add Price', max_length=100, null=True),
        ),
    ]
