# Generated by Django 3.1.4 on 2022-04-07 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0048_auto_20220407_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentTermFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_work', models.BooleanField(default=False)),
                ('fob', models.BooleanField(default=False)),
                ('cif', models.BooleanField(default=False)),
                ('ddp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Payment Term Field',
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='minimum_order_quantity',
            new_name='maximum_order_quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.productinventory'),
        ),
        migrations.AddField(
            model_name='product',
            name='terms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.paymenttermfields'),
        ),
    ]
