# Generated by Django 3.1.4 on 2022-04-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0049_auto_20220407_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='maximum_order_quantity',
            new_name='minimum_order_quantity',
        ),
    ]
