# Generated by Django 3.1.4 on 2022-04-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0052_remove_product_terms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentTermFields',
        ),
    ]
