# Generated by Django 3.1.4 on 2022-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0053_delete_paymenttermfields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_choice',
            field=models.CharField(blank=True, choices=[('Add Price', 'Add Price'), ('Price according to quantity', 'Price according to quantity')], max_length=100, null=True),
        ),
    ]
