# Generated by Django 3.1.4 on 2022-04-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0054_auto_20220407_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='maximum_order_quantity',
        ),
    ]
