# Generated by Django 3.1.4 on 2022-04-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0059_remove_product_main_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_category',
        ),
    ]
