# Generated by Django 3.1.4 on 2022-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0061_product_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='state',
            new_name='country',
        ),
        migrations.AddField(
            model_name='port',
            name='latitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='longitude',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
