# Generated by Django 3.1.4 on 2022-04-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0064_auto_20220417_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Completed', 'Completed')], max_length=1000, null=True),
        ),
    ]
