# Generated by Django 3.1.4 on 2022-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0065_auto_20220417_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='feedback',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(null=True),
        ),
    ]
