# Generated by Django 3.1.4 on 2022-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0067_auto_20220417_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='primary_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('prod_category', models.ManyToManyField(to='negbuyapi.productCategory')),
            ],
        ),
    ]
