# Generated by Django 3.1.4 on 2022-04-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0070_auto_20220418_0636'),
        ('negbuyapi', '0070_auto_20220418_1406'),
    ]

    operations = [
    ]
