# Generated by Django 3.1.2 on 2022-05-11 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0071_auto_20220511_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq_db',
            name='target_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='buyer_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('feedback', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.userdb')),
            ],
            options={
                'verbose_name_plural': 'Buyer_Questions',
            },
        ),
    ]
