# Generated by Django 3.1.2 on 2022-05-12 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0073_auto_20220511_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_questions',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.product'),
        ),
    ]
