# Generated by Django 3.1.4 on 2022-04-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0074_auto_20220422_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
