# Generated by Django 3.1.2 on 2022-06-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0075_db_rfq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DB_rfq',
            new_name='rfq',
        ),
        migrations.AlterModelOptions(
            name='rfq',
            options={'verbose_name_plural': 'rfq'},
        ),
    ]
