# Generated by Django 3.1.4 on 2022-04-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0075_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_date', models.DateTimeField(auto_now=True, null=True)),
                ('order_time', models.TimeField(null=True)),
                ('order_quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('shipping_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, choices=[('Running', 'Running'), ('Completed', 'Completed')], max_length=1000, null=True)),
                ('feedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('order_note', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.userdb')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
