# Generated by Django 3.1.2 on 2022-06-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0077_auto_20220423_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='userdb',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
