# Generated by Django 3.1.3 on 2022-05-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0078_auto_20220517_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('review', models.CharField(blank=True, max_length=1000, null=True)),
                ('rating', models.CharField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.DeleteModel(
            name='video_db',
        ),
        migrations.AddField(
            model_name='product',
            name='page_status',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productimages',
            name='color',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productimages',
            name='main_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimages',
            name='size',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='review_db',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.product'),
        ),
        migrations.AddField(
            model_name='review_db',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.userdb'),
        ),
    ]
