# Generated by Django 3.1.3 on 2022-06-16 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negbuyapi', '0079_auto_20220518_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=1000, null=True)),
                ('size', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='product_detail_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, upload_to='New_Images')),
                ('heading', models.CharField(blank=True, max_length=1000, null=True)),
                ('desc', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Details',
            },
        ),
        migrations.CreateModel(
            name='rfq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('target_price', models.IntegerField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'RFQs',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory_id',
        ),
        migrations.AddField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=15000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='varients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos'),
        ),
        migrations.AddField(
            model_name='userdb',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bankDetails', to='negbuyapi.userdb'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='negbuyapi.userdb'),
        ),
        migrations.AlterField(
            model_name='review_db',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='negbuyapi.product'),
        ),
        migrations.AlterField(
            model_name='review_db',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.DeleteModel(
            name='productInventory',
        ),
        migrations.AddField(
            model_name='rfq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negbuyapi.userdb'),
        ),
        migrations.AddField(
            model_name='product_detail_db',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_details', to='negbuyapi.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='negbuyapi.product'),
        ),
    ]
